const resList = [
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255963",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.2,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255964",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.5,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255965",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.8,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255966",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.9,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255967",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.5,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255967",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.7,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
  {
    card: {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
        info: {
          id: "255967",
          name: "Mama Mia Pizza",
          cloudinaryImageId: "dbe9ce80ac4d20560005cea827db31fb",
          locality: "Sector 7",
          areaName: "Sector 7",
          costForTwo: "₹300 for two",
          cuisines: ["Pizzas", "Pastas", "Beverages", "Desserts"],
          avgRating: 4.3,
          parentId: "131084",
          avgRatingString: "4.2",
          totalRatingsString: "2.2K+",
          sla: {
            deliveryTime: 26,
            lastMileTravel: 1.8,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "1.8 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
      },
    },
  },
];
export default resList;
